# PIPELINE DEFINITION
# Name: pythagorean
# Inputs:
#    a: float [Default: 1.2]
#    b: float [Default: 1.2]
# Outputs:
#    Output: float
components:
  comp-add:
    executorLabel: exec-add
    inputDefinitions:
      parameters:
        x:
          parameterType: NUMBER_DOUBLE
        y:
          parameterType: NUMBER_DOUBLE
    outputDefinitions:
      parameters:
        Output:
          parameterType: NUMBER_DOUBLE
  comp-square:
    executorLabel: exec-square
    inputDefinitions:
      parameters:
        x:
          parameterType: NUMBER_DOUBLE
    outputDefinitions:
      parameters:
        Output:
          parameterType: NUMBER_DOUBLE
  comp-square-2:
    executorLabel: exec-square-2
    inputDefinitions:
      parameters:
        x:
          parameterType: NUMBER_DOUBLE
    outputDefinitions:
      parameters:
        Output:
          parameterType: NUMBER_DOUBLE
  comp-square-and-sum:
    dag:
      outputs:
        parameters:
          Output:
            valueFromParameter:
              outputParameterKey: Output
              producerSubtask: add
      tasks:
        add:
          cachingOptions:
            enableCache: true
          componentRef:
            name: comp-add
          dependentTasks:
          - square
          - square-2
          inputs:
            parameters:
              x:
                taskOutputParameter:
                  outputParameterKey: Output
                  producerTask: square
              y:
                taskOutputParameter:
                  outputParameterKey: Output
                  producerTask: square-2
          taskInfo:
            name: add
        square:
          cachingOptions:
            enableCache: true
          componentRef:
            name: comp-square
          inputs:
            parameters:
              x:
                componentInputParameter: a
          taskInfo:
            name: square
        square-2:
          cachingOptions:
            enableCache: true
          componentRef:
            name: comp-square-2
          inputs:
            parameters:
              x:
                componentInputParameter: b
          taskInfo:
            name: square-2
    inputDefinitions:
      parameters:
        a:
          parameterType: NUMBER_DOUBLE
        b:
          parameterType: NUMBER_DOUBLE
    outputDefinitions:
      parameters:
        Output:
          parameterType: NUMBER_DOUBLE
  comp-square-root:
    executorLabel: exec-square-root
    inputDefinitions:
      parameters:
        x:
          parameterType: NUMBER_DOUBLE
    outputDefinitions:
      parameters:
        Output:
          parameterType: NUMBER_DOUBLE
deploymentSpec:
  executors:
    exec-add:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - add
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet     --no-warn-script-location 'kfp==2.0.1'\
          \ && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)

          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          python3 -m kfp.components.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef add(x: float, y: float) -> float:\n    return x + y\n\n"
        image: python:3.7
    exec-square:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - square
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet     --no-warn-script-location 'kfp==2.0.1'\
          \ && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)

          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          python3 -m kfp.components.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef square(x: float) -> float:\n    return x ** 2\n\n"
        image: python:3.7
    exec-square-2:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - square
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet     --no-warn-script-location 'kfp==2.0.1'\
          \ && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)

          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          python3 -m kfp.components.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef square(x: float) -> float:\n    return x ** 2\n\n"
        image: python:3.7
    exec-square-root:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - square_root
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet     --no-warn-script-location 'kfp==2.0.1'\
          \ && \"$0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)

          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          python3 -m kfp.components.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef square_root(x: float) -> float:\n    return x ** .5\n\n"
        image: python:3.7
pipelineInfo:
  name: pythagorean
root:
  dag:
    outputs:
      parameters:
        Output:
          valueFromParameter:
            outputParameterKey: Output
            producerSubtask: square-root
    tasks:
      square-and-sum:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-square-and-sum
        inputs:
          parameters:
            a:
              componentInputParameter: a
            b:
              componentInputParameter: b
        taskInfo:
          name: square-and-sum
      square-root:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-square-root
        dependentTasks:
        - square-and-sum
        inputs:
          parameters:
            x:
              taskOutputParameter:
                outputParameterKey: Output
                producerTask: square-and-sum
        taskInfo:
          name: square-root
  inputDefinitions:
    parameters:
      a:
        defaultValue: 1.2
        isOptional: true
        parameterType: NUMBER_DOUBLE
      b:
        defaultValue: 1.2
        isOptional: true
        parameterType: NUMBER_DOUBLE
  outputDefinitions:
    parameters:
      Output:
        parameterType: NUMBER_DOUBLE
schemaVersion: 2.1.0
sdkVersion: kfp-2.0.1
