name: MLOps-Pipeline-Started!
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install -r requirements.txt

          python src/dataIngestion.py  # generate plot.png
          python src/preprocess.py
          python src/train.py

          # Create CML report
          cat metrics.json >> README.md
          echo '![](images/confusion_matrix.png "Confusion Matrix")' >> README.md
        #   cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}