name: MLOps-Pipeline-Started!
on: 
  push:
    branches:
      - main
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Model Training
        run: |
          python src/dataIngestion.py  
          python src/preprocess.py
          python src/train.py

          # Create CML report
          echo "### Model Score" >> README.md
          echo metrics.txt >> README.md
          cml comment images/confusion_matrix.png --md >> README.md
        
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Docker Image Build
        run: |
          echo "${{ secrets.DOCKERPW }}" | docker login -u "krisharyan36" --password-stdin
          docker image build -t argocd:latest .
          docker push argocd:latest
